export const FIRST_DOOR_IN_REQUEST = "FIRST_DOOR_IN_REQUEST";
export const FIRST_DOOR_IN_REQUEST_SUCCESS = "FIRST_DOOR_IN_REQUEST_SUCCESS";
export const FIRST_DOOR_IN_REQUEST_ERROR = "FIRST_DOOR_IN_REQUEST_ERROR";


export const CHANGE_SCREEN_REQUEST ="CHANGE_SCREEN_REQUEST";
export const CHANGE_SCREEN_SUCCESS = "CHANGE_SCREEN_SUCCESS";

export const SECOND_DOOR_IN_REQUEST = "SECOND_DOOR_IN_REQUEST";
export const SECOND_DOOR_IN_REQUEST_SUCCESS = "SECOND_DOOR_IN_REQUEST_SUCCESS";
export const SECOND_DOOR_IN_REQUEST_ERROR = "SECOND_DOOR_IN_REQUEST_ERROR";



export const THIRD_DOOR_IN_REQUEST = "THIRD_DOOR_IN_REQUEST";
export const THIRD_DOOR_IN_REQUEST_SUCCESS = "THIRD_DOOR_IN_REQUEST_SUCCESS";
export const THIRD_DOOR_IN_REQUEST_ERROR = "THIRD_DOOR_IN_REQUEST_ERROR";